language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
before_install:
  - sudo add-apt-repository ppa:jblgf0/outros3-precise -y
  - sudo apt-get update
  - sudo apt-get install libsecret-1-dev -y
